### PR TITLE
Noe/add meta tag max size

### PR DESCRIPTION
**Pull request by nmalzieu**
Now that the proxy server handles a meta tag max size parameter, add it to the proxy client

### CODE REVIEW

**Comment by neekolas** [comment]
Looks good to me. Think you'll need to rebase or merge against main to get the true diff, since I see duplicate commits.

**Comment by nmalzieu** [comment]
> Looks good to me. Think you'll need to rebase or merge against main to get the true diff, since I see duplicate commits.

sorry about that! should be fixed now.

**Review by neekolas — DISMISSED** [review]

**Review by alexrisch — DISMISSED** [review]

**Comment by neekolas** [comment]
You'll also want to run yarn changeset so that this publishes a new version of the library

**Comment by nmalzieu** [comment]
@neekolas done

**Review by neekolas — APPROVED** [review]

**Pull request merged**
